### ISSUE TITLE
#TK09 Armado del modelo Entidad Relación

### ISSUE THREAD

**Issue by lucantu97** [guillevla/Grupo19-Proyecto-integrador-2-cuatri-TSDWAD#10]
Debemos ir dándole forma a la base de datos, por ello vamos a comenzar con el modelo **Entidad Relació**n. Suban en sus ramas personales los modelos, comenten en esta Issue que se puede mejorar. @Laurix86 @DiegoGuardatti

**Comment by DiegoGuardatti** [comment]
Subí a mi rama un modelo de la base de datos.

**Comment by lucantu97** [comment]
Esta buenisima Diego!!! Use de base ese diagrama y cree 3 Tablas, lo subi en mi rama.

**Comment by guillevla** [comment]
tarea realizada
