### ISSUE TITLE
#TK07 Realizar sección "Quienes Somos"

### ISSUE THREAD

**Issue by lucantu97** [guillevla/Grupo19-Proyecto-integrador-2-cuatri-TSDWAD#13]
Para esta sección tenemos que responder esta gran pregunta, _¿Cuál es nuestra misión?_ La respuesta tiene que ser desarrollada de una manera clara y concisa, dejando saber al cliente cuales son nuestros objetivos. **¡Todos debemos participar!**

**Comment by DiegoGuardatti** [comment]
Subí mi aporte sobre esta sección

**Comment by guillevla** [comment]
Buen dia, subi en mi rama Quienes somos

**Comment by Laurix86** [comment]
Buenas, les comparto lo que había empezado a escribir para esta sección. Ahora que leí lo de ustedes creo que arranqué para otro lado. 
_QUIENES SOMOS - Nuestro camino comenzó cuando, de forma azarosa, coincidimos estudiando en el ISPC y conformamos un grupo siendo desconocidos estando a kilómetros de distancia. Con el transcurso del cuatrimestre logramos superar múltiples barreras y dificultades, hacia el fin de ese año descubrimos que, no sólo habíamos alcanzado los objetivos curriculares sino que además habíamos pasado de ser un grupo de estudio a un equipo de trabajo. 
Así nos decidimos a conformar esta empresa dedicada al desarrollo de soluciones tecnológicas de software a medida ... _

**Comment by claudio-plaza** [comment]
@Laurix86  muy bueno tu aporte. Muy pronto subo lo mio

**Comment by guillevla** [comment]
tarea realizada
