### ISSUE TITLE
Creacion Nombre empresa para Web

### ISSUE THREAD

**Issue by guillevla** [guillevla/Grupo19-Proyecto-integrador-2-cuatri-TSDWAD#2]

**Comment by DiegoGuardatti** [comment]
Mi propuesta parda darle un nombre de la empresa sería NIMBUS Sistemas informáticos.

**Comment by AntonellaBayon** [comment]
Me gusta.

**Comment by claudio-plaza** [comment]
Exelente

**Comment by DiegoGuardatti** [comment]
Quiero proponer como nombre del sistema: _**Plataforma Integral de Gestión de Danzas en sus siglas PIGAD**_

**Comment by guillevla** [comment]
Nombre de empresa elegido
