### ISSUE TITLE
#TK08 Crear la primera estructura semántica de la página web

### ISSUE THREAD

**Issue by guillevla** [guillevla/Grupo19-Proyecto-integrador-2-cuatri-TSDWAD#5]

**Comment by lucantu97** [comment]
Debemos de crear la primera estructura, para ellos usaremos **HTML** para dar forma a la página y adicionalmente usaremos **CSS** para darle estilo. Recordar que subiremos en nuestras ramas personales los trabajos propios, para luego verificarlos o modificarlos y subir a la rama de Desarrollo. _¡Lo dejamos en sus manos!_ @claudio-plaza @Hhologram @guillevla @claudio-plaza @AntonellaBayon @alfreedo655

**Comment by DiegoGuardatti** [comment]
En mi rama, subí mi aporte sobre la estructura html, es solo un bosquejo de como pensé la página de inicio del proyecto, sobre el código de Claudio.

**Comment by guillevla** [comment]
Subi una primer esquema de pagina web.

**Comment by guillevla** [comment]
tarea realizada
